---
apiVersion: v2
appVersion: 1.1.3
description: Bazarr is a companion application to Sonarr and Radarr. It manages and downloads subtitles based on your requirements
name: bazarr
version: 1.1.0
kubeVersion: ">=1.22.0-0"
keywords:
  - bazarr
  - radarr
  - sonarr
  - subtitles
  - usenet
  - torrent
home: https://bjw-s.github.io/helm-charts/
icon: https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/bazarr.png
sources:
  - https://github.com/morpheus65535/bazarr
  - https://bjw-s.github.io/helm-charts/
maintainers:
  - name: D-o-c
    email: helmcharts@docstwocents.com	
dependencies:
  - name: common
    repository: https://bjw-s.github.io/helm-charts
    version: 1.2.0
annotations:
  artifacthub.io/changes: |-
        - kind: changed
          description: |
            Updated library version to 1.2.0.
          links:
            - name: Common library chart definition
              url: https://github.com/bjw-s/helm-charts/blob/main/charts/library/common/Chart.yaml
        - kind: changed
          description: |
            Updated app version to 1.1.3.
