{{- include "bjw-s.common.loader.init" . }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "bjw-s.common.lib.chart.names.name" . }}-config
  labels:
    {{- include "common.labels" . | nindent 4 }}
data:
  AdGuardHome.yaml: |
{{ .Values.config | indent 4 }}
