---
apiVersion: v2
appVersion: v2.2.10
description: FlareSolverr is a proxy server to bypass Cloudflare protection
name: flaresolverr
version: 1.1.1
kubeVersion: ">=1.16.0-0"
maintainers:
  - name: Doc
    email: doc@doctwocents.com
dependencies:
- name: common
  version: 1.1.3
  repository: https://bjw-s.github.io/helm-charts/
annotations:
  artifacthub.io/changes: |-
    - kind: changed
      description: |
        Updated library version to 1.1.3.
      links:
        - name: Common library chart definition
          url: https://github.com/bjw-s/helm-charts/blob/main/charts/library/common/Chart.yaml
    - kind: changed
      description: |
        Added mantainer
