---
apiVersion: v2
appVersion: 1.9.2
description: Paperless - Index and archive all of your scanned paper documents
name: paperless
version: 1.1.3
kubeVersion: ">=1.22.0-0"
keywords:
  - paperless
home: https://bjw-s.github.io/helm-charts/
icon: https://avatars.githubusercontent.com/u/47271576?s=200&v=4
sources:
  - https://github.com/paperless-ngx/paperless-ngx
maintainers:
  - name: D-o-c
    email: helmcharts@docstwocents.com	
dependencies:
  - name: common
    repository: https://bjw-s.github.io/helm-charts
    version: 1.1.3
  - name: postgresql
    version: 11.6.12
    repository: https://charts.bitnami.com/bitnami
    condition: postgresql.enabled
  - name: redis
    version: 16.13.1
    repository: https://charts.bitnami.com/bitnami
    condition: redis.enabled
annotations:
  artifacthub.io/changes: |-
    - kind: changed
      description: |
        Updated library version to 1.1.3.
      links:
        - name: Common library chart definition
          url: https://github.com/bjw-s/helm-charts/blob/main/charts/library/common/Chart.yaml
