{{- include "bjw-s.common.loader.init" . -}}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "bjw-s.common.lib.chart.names.name" . }}-settings
  labels:
    {{- include "bjw-s.common.lib.metadata.allLabels" . | nindent 4 }}
data:
  configuration.yaml: |
{{- with .Values.config }}
    {{- toYaml . | nindent 4 }}
{{- end }}
