---
{{- include "bjw-s.common.loader.init" . }}

{{- define "app-template.hardcodedValues" -}}
# Set the nameOverride based on the release name if no override has been set
{{ if not .Values.global.nameOverride }}
global:
  nameOverride: "{{ .Release.Name }}"
{{ end }}
{{- end -}}
{{- $_ := mergeOverwrite .Values (include "app-template.hardcodedValues" . | fromYaml) -}}

{{/* Append the configMap volume to the volumes */}}
{{- define "mosquitto.configVolume" -}}
enabled: "true"
mountPath: "/mosquitto/config/mosquitto.conf"
subPath: "mosquitto.conf"
type: "custom"
volumeSpec:
  configMap:
    name: {{ include "bjw-s.common.lib.chart.names.fullname" . }}-config
{{- end -}}
{{- $_ := set .Values.persistence "mosquitto-config" (include "mosquitto.configVolume" . | fromYaml) -}}

{{/* Create the configMap elements */}}
{{- define "mosquitto.configMap" -}}
enabled: true
#name: {{ include "bjw-s.common.lib.chart.names.fullname" . }}-config
labels:
  {{- include "bjw-s.common.lib.metadata.allLabels" . | nindent 4 }}
data:
  mosquitto.conf: |
    per_listener_settings {{ .Values.perListenerSettings }}
    {{- if .Values.addListener }}
    listener {{ .Values.service.main.ports.mqtt.port }}
    {{- end}}
    {{- if .Values.auth.enabled }}
    allow_anonymous false
    {{- else }}
    allow_anonymous true
    {{- end }}
    {{- if .Values.persistence.data.enabled }}
    persistence true
    persistence_location {{ .Values.persistence.data.mountPath }}
    autosave_interval 1800
    {{- end }}
    {{- if .Values.persistence.configinc.enabled }}
    include_dir {{ .Values.persistence.configinc.mountPath }}
    {{- end }}
{{- end -}}
{{- $_ := set .Values.configMaps "config" (include "mosquitto.configMap" . | fromYaml) -}}

{{/* Render the templates */}}
{{ include "bjw-s.common.loader.generate" . }}
