---
apiVersion: v2
description: Creates ingress reverse-proxies for external hosts with minimum boilerplate
name: reverse-proxy
version: 1.0.0
kubeVersion: ">=1.22.0-0"
maintainers:
  - name: D-o-c
    email: helmcharts@docstwocents.com	
keywords:
  - reverse-proxy
  - ingress
home: https://bjw-s.github.io/helm-charts/
icon: https://kubernetes.io/images/wheel.svg
sources:
  - https://kubernetes.io/docs/concepts/services-networking/ingress/
dependencies:
  - name: common
    repository: https://bjw-s.github.io/helm-charts
    version: 1.1.3
annotations:
  artifacthub.io/changes: |-
    - kind: added
      description: first release
