---
apiVersion: v2
appVersion: v2.1.1
description: Deluge is a torrent download client
name: deluge
version: 1.1.3
kubeVersion: ">=1.22.0-0"
keywords:
  - deluge
  - torrent
home: https://bjw-s.github.io/helm-charts/
icon: https://avatars2.githubusercontent.com/u/6733935?v=3&s=200
sources:
  - https://hub.docker.com/r/linuxserver/deluge/
  - https://deluge-torrent.org/
maintainers:
  - name: D-o-c
    email: helmcharts@docstwocents.com	
dependencies:
  - name: common
    repository: https://bjw-s.github.io/helm-charts
    version: 1.1.3
annotations:
  artifacthub.io/changes: |-
    - kind: changed
      description: |
        Updated library version to 1.1.3.
      links:
        - name: Common library chart definition
          url: https://github.com/bjw-s/helm-charts/blob/main/charts/library/common/Chart.yaml
