{{- if and .Values.metrics.enabled .Values.metrics.prometheusRule.enabled }}
{{- include "bjw-s.common.loader.init" . }}
---
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: {{ include "bjw-s.common.lib.chart.names.name" . }}
  labels:
    {{- include "bjw-s.common.lib.metadata.allLabels" . | nindent 4 }}
    {{- with .Values.metrics.prometheusRule.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  groups:
    - name: {{ include "bjw-s.common.lib.chart.names.name" . }}
      rules:
        - alert: ExportarrAbsent
          annotations:
            description: Sonarr Exportarr has disappeared from Prometheus
              service discovery.
            summary: Exportarr is down.
          expr: |
            absent(up{job=~".*{{ include "bjw-s.common.lib.chart.names.name" . }}.*"} == 1)
          for: 5m
          labels:
            severity: critical
        - alert: SonarrDown
          annotations:
            description: Sonarr service is down.
            summary: Sonarr is down.
          expr: |
            sonarr_system_status{job=~".*{{ include "bjw-s.common.lib.chart.names.name" . }}.*"} == 0
          for: 5m
          labels:
            severity: critical
        {{- with .Values.metrics.prometheusRule.rules }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
{{- end }}
